name: Java CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Test with Gradle
        run: ./gradlew --no-daemon --continue test
      - name: Create test summary
        uses: test-summary/action@62bc5c68de2a6a0d02039763b8c754569df99e3f
        with:
          paths: "**/build/test-results/test/*.xml"
        if: always()

  smoke_tests:
    name: Smoke tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
        with:
          install: true

      - name: Build Docker image and store in cache
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: false
          load: true
          tags: exercism/java-representer
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests in Docker
        run: bin/run-tests-in-docker.sh
